export const thirdPlaceTable = [
  {
    position: 3,
    played: 0,
    team_id: 18645,
    team_name: "England",
    short_code: "ENG",
    team_logo: "https://cdn.sportmonks.com/images/soccer/teams/21/18645.png",
    goals: "0:0",
    goal_diff: 0,
    wins: 0,
    lost: 0,
    draws: 0,
    points: 0,
    description: "Possible 8th Finals",
    recent_form: "",
    fairplay_points_lose: 0,
  },
  {
    position: 3,
    played: 0,
    team_id: 18710,
    team_name: "Spain",
    short_code: "ESP",
    team_logo: "https://cdn.sportmonks.com/images/soccer/teams/22/18710.png",
    goals: "0:0",
    goal_diff: 0,
    wins: 0,
    lost: 0,
    draws: 0,
    points: 0,
    description: "Possible 8th Finals",
    recent_form: "",
    fairplay_points_lose: 0,
  },
  {
    position: 3,
    played: 0,
    team_id: 18716,
    team_name: "Turkey",
    short_code: "TUR",
    team_logo: "https://cdn.sportmonks.com/images/soccer/teams/28/18716.png",
    goals: "0:0",
    goal_diff: 0,
    wins: 0,
    lost: 0,
    draws: 0,
    points: 0,
    description: "Possible 8th Finals",
    recent_form: "",
    fairplay_points_lose: 0,
  },
  {
    position: 3,
    played: 0,
    team_id: 18570,
    team_name: "Finland",
    short_code: "FIN",
    team_logo: "https://cdn.sportmonks.com/images/soccer/teams/10/18570.png",
    goals: "0:0",
    goal_diff: 0,
    wins: 0,
    lost: 0,
    draws: 0,
    points: 0,
    description: "Possible 8th Finals",
    recent_form: "",
    fairplay_points_lose: 0,
  },
  {
    position: 3,
    played: 0,
    team_id: 18689,
    team_name: "North Macedonia",
    short_code: "MKD",
    team_logo: "https://cdn.sportmonks.com/images/soccer/teams/1/18689.png",
    goals: "0:0",
    goal_diff: 0,
    wins: 0,
    lost: 0,
    draws: 0,
    points: 0,
    description: "Possible 8th Finals",
    recent_form: "",
    fairplay_points_lose: 0,
  },
  {
    position: 3,
    played: 0,
    team_id: 18732,
    team_name: "Hungary",
    short_code: "HUN",
    team_logo: "https://cdn.sportmonks.com/images/soccer/teams/12/18732.png",
    goals: "0:0",
    goal_diff: 0,
    wins: 0,
    lost: 0,
    draws: 0,
    points: 0,
    description: "Possible 8th Finals",
    recent_form: "",
    fairplay_points_lose: 0,
  },
];
